version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - sam package --template-file SayNoToUILibraries-backend/template.yaml --s3-bucket codepipeline-ap-southeast-1-973077307486 --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml
